// Generated by CoffeeScript 2.3.0
(function() {
  'use strict';
  var FileStream, Template, URLHandlers, handlers, http, layout, server, stream;

  URLHandlers = require('./coffee/compiled/URLHandlers.js');

  FileStream = require('./coffee/compiled/FileStream.js');

  Template = require('./coffee/compiled/Template.js');

  http = require('http');

  stream = new FileStream('data');

  layout = new Template('views', 'layout');

  if (!stream.file('profiles.json')) {
    stream.file('profiles.json', '{}');
  }

  handlers = new URLHandlers().add('GET', /\.[a-z\-]+$/i, URLHandlers.static('static')).add('GET', '/', function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    return res.end('Hello.');
  }).add('GET', '/profile/:id', function(req, res) {
    var profiles;
    profiles = JSON.parse(stream.file('profiles.json'));
    if (req.params.id in profiles) {
      res.writeHead(200, {
        'Content-Type': 'text/html'
      });
      return res.end(layout.render('profile', profiles[req.params.id]));
    } else {
      res.writeHead(404, {
        'Content-Type': 'text/html'
      });
      return res.end(layout.render('error', {
        status: 404,
        message: 'Unknown profile.'
      }));
    }
  });

  server = http.createServer(function(req, res) {
    var handler;
    req.url = handlers.parseURL(req);
    if ((handler = handlers.handle(req, res))) {
      return handler(req, res);
    } else {

    }
  });

  // send an error
  server.listen(9000, function() {
    return console.log('Listening "http://localhost:9000/"...');
  });

}).call(this);

//# sourceMappingURL=server.js.map
