// Generated by CoffeeScript 2.3.0
(function() {
  'use strict';
  var URLHandlers, fs, handlers, http, server, template;

  URLHandlers = require('./scripts/URLHandlers.js');

  template = require('./scripts/template.js');

  http = require('http');

  fs = require('fs');

  handlers = new URLHandlers().add('GET', '/', function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    return res.end('Hello.');
  }).add('GET', '/:name', function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    return res.end(req.params.name);
  });

  server = http.createServer(function(req, res) {
    var handler;
    if ((handler = handlers.handle(req, res))) {
      return handler(req, res);
    } else {

    }
  });

  // send an error
  server.listen(9000, function() {
    return console.log('Listening "http://localhost:9000/"...');
  });

}).call(this);

//# sourceMappingURL=server.js.map
