// Generated by CoffeeScript 2.3.0
(function() {
  // Based on JSDoc template.js
  'use strict';
  var Template, _, fs;

  fs = require('fs');

  _ = require('underscore');

  module.exports = function(path, layout, settings) {
    return new Template(path, layout, settings);
  };

  module.exports.Template = Template = (function() {
    class Template {
      constructor(path1, layout1, settings) {
        this.path = path1;
        this.layout = layout1;
        if (typeof settings === 'string') {
          this.settings = {
            variable: settings
          };
        } else {
          this.settings = settings || Object.assign({}, Template.settings);
        }
        this.cache = {};
      }

      load(path) {
        return _.template(fs.readFileSync(path, 'utf8'), this.settings);
      }

      partial(path, data) {
        path = this.path + path;
        if (!(path in this.cache)) {
          this.cache[path] = this.load(path);
        }
        return this.cache[path].call(this, data);
      }

      render(path, data) {
        data.content = this.partial(path, data);
        return this.partial(this.layout, data);
      }

    };

    Template.settings = {
      variable: 'data'
    };

    return Template;

  }).call(this);

}).call(this);

//# sourceMappingURL=template.js.map
