// Generated by CoffeeScript 2.3.0
(function() {
  'use strict';
  module.exports = class {
    constructor() {
      this.handlers = [];
    }

    add(method, pattern, handler) {
      var params;
      params = [];
      if (typeof pattern === 'string') {
        pattern = pattern.replace(/:([_a-z][_a-z0-9]*)/g, function(a, b) {
          if (!~params.indexOf(b)) {
            params.push(b);
          } else {
            throw Error('You have the same param name: ' + b);
          }
          return '([^/]+?)';
        });
        pattern = RegExp('^' + pattern + '/?$');
      }
      this.handlers.push({method, pattern, handler, params});
      return this;
    }

    handle(req, res) {
      var handler, i, j, k, len, match, method, params, pattern, ref, ref1;
      ref = this.handlers;
      for (j = 0, len = ref.length; j < len; j++) {
        ({method, pattern, handler, params} = ref[j]);
        if (!(method === req.method && (match = pattern.exec(req.url)))) {
          continue;
        }
        req.params = {};
        for (i = k = 0, ref1 = params.length; (0 <= ref1 ? k < ref1 : k > ref1); i = 0 <= ref1 ? ++k : --k) {
          req.params[params[i]] = match[i + 1];
        }
        return handler;
      }
    }

  };

}).call(this);

//# sourceMappingURL=URLHandlers.js.map
