// Generated by CoffeeScript 2.3.0
(function() {
  'use strict';
  var fs;

  fs = require('fs');

  module.exports = class {
    constructor(path) {
      this.path = path;
      this.loaded = false;
    }

    read() {
      if (!this.loaded) {
        if (fs.existsSync(this.path)) {
          this.content = fs.readFileSync(this.path, 'utf8');
          this.loaded = true;
        } else {
          this.content = '';
        }
      }
      return this.content;
    }

    write(content) {
      // i think that better is to reset cache
      return fs.writeFileSync(this.path, this.content = content);
    }

  };

}).call(this);

//# sourceMappingURL=File.js.map
