// Generated by CoffeeScript 2.3.0
(function() {
  'use strict';
  var File, path;

  File = require('./File.js');

  path = require('path');

  module.exports = class {
    constructor(scope) {
      this.scope = scope;
      this.cache = {};
    }

    file(filepath, content) {
      filepath = path.join(this.scope, filepath);
      if (!(filepath in this.cache)) {
        this.cache[filepath] = new File(filepath);
      }
      if (content != null) {
        return this.cache[filepath].write(content);
      } else {
        return this.cache[filepath].read();
      }
    }

  };

}).call(this);

//# sourceMappingURL=FileStream.js.map
