// Generated by CoffeeScript 2.3.0
(function() {
  // Based on JSDoc template.js
  'use strict';
  var _, fs, path;

  path = require('path');

  fs = require('fs');

  _ = require('underscore');

  module.exports = (function() {
    var _Class;

    _Class = class {
      constructor(scope, layout, settings) {
        this.scope = scope;
        this.layout = layout;
        if (typeof settings === 'string') {
          this.settings = {
            variable: settings
          };
        } else {
          this.settings = settings || Object.assign({}, module.exports.settings);
        }
        this.cache = {};
      }

      _load(templatePath) {
        return _.template(fs.readFileSync(templatePath + '.tmpl', 'utf8'), this.settings);
      }

      partial(templatePath, data) {
        templatePath = path.join(this.scope, templatePath);
        if (!(templatePath in this.cache)) {
          this.cache[templatePath] = this._load(templatePath);
        }
        return this.cache[templatePath].call(this, data);
      }

      render(templatePath, data) {
        data.content = this.partial(templatePath, data);
        return this.partial(this.layout, data);
      }

    };

    _Class.settings = {
      variable: 'data'
    };

    return _Class;

  }).call(this);

}).call(this);

//# sourceMappingURL=Template.js.map
